# Generated by Django 4.1.1 on 2022-09-09 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('usermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cnpj', models.CharField(max_length=14)),
                ('ministery', models.CharField(max_length=14)),
                ('name', models.CharField(max_length=80)),
                ('fundation', models.DateField()),
                ('contact', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
            bases=('user.usermodel',),
        ),
    ]
