# Generated by Django 4.1.1 on 2022-09-17 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('informations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14)),
                ('ministery', models.CharField(max_length=14)),
                ('name', models.CharField(max_length=80)),
                ('adress', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='informations.adress')),
                ('bankData', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='informations.bankdata')),
                ('pix', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='informations.pix')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
