# Generated by Django 4.1.1 on 2022-09-13 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='church',
            name='fundation',
        ),
    ]
