# Generated by Django 4.1.1 on 2022-09-19 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0001_initial'),
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='adress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='informations.adress'),
        ),
        migrations.AlterField(
            model_name='church',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
