# Generated by Django 4.1.1 on 2022-09-17 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_remove_church_fundation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='church',
            name='contact',
        ),
    ]
