# Generated by Django 4.1.1 on 2022-11-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0006_alter_church_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='ministery',
            field=models.CharField(max_length=50),
        ),
    ]
