# Generated by Django 4.1.1 on 2022-09-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=18)),
                ('bank', models.CharField(max_length=12)),
                ('agency', models.CharField(max_length=5)),
                ('agencyDigit', models.IntegerField()),
                ('account', models.CharField(max_length=20)),
                ('accountDigit', models.IntegerField()),
                ('accountType', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pix',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('categoryKey', models.CharField(max_length=20)),
                ('key', models.CharField(max_length=32)),
            ],
        ),
    ]
