# Generated by Django 4.1.1 on 2022-10-10 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='voucher',
        ),
    ]
