# Generated by Django 4.1.1 on 2022-10-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_remove_donation_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='voucher',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
