# Generated by Django 4.1.1 on 2022-10-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_donation_valid_donation_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='payment_form',
            field=models.CharField(max_length=50),
        ),
    ]
