# Generated by Django 4.1.1 on 2022-10-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_alter_donation_payment_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='recused',
            field=models.BooleanField(default=False),
        ),
    ]
