# Generated by Django 4.1.1 on 2022-09-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=9)),
                ('adress', models.CharField(blank=True, max_length=80, null=True)),
                ('number', models.CharField(blank=True, max_length=9, null=True)),
                ('city', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('district', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder', models.CharField(max_length=80)),
                ('cnpj', models.CharField(max_length=14)),
                ('bank', models.CharField(max_length=8)),
                ('agency', models.CharField(max_length=5)),
                ('digitAgency', models.CharField(max_length=1)),
                ('account', models.CharField(max_length=20)),
                ('digitAccount', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PIX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeKey', models.CharField(max_length=10)),
                ('valueKey', models.CharField(max_length=100)),
            ],
        ),
    ]
