# Generated by Django 4.1.1 on 2022-09-20 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='adress',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='informations.adress'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='id_adress',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
