# Generated by Django 4.1.1 on 2022-09-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_adress_project_id_adress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='personResponsible',
        ),
        migrations.AddField(
            model_name='project',
            name='id_church',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='id_adress',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
