# Generated by Django 4.1.1 on 2022-10-07 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_information_informationproject_usermodel_information'),
        ('project', '0005_follower_project_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='information',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.informationproject'),
            preserve_default=False,
        ),
    ]
