# Generated by Django 4.1.1 on 2022-10-07 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_project_information'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='information',
            new_name='information_profile',
        ),
    ]
