# Generated by Django 4.1.1 on 2022-10-07 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_usermodel_information'),
        ('project', '0007_rename_information_project_information_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='information_profile',
        ),
        migrations.AddField(
            model_name='project',
            name='information',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.information'),
            preserve_default=False,
        ),
    ]
