# Generated by Django 4.1.1 on 2022-10-07 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0008_remove_project_information_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='followers',
        ),
        migrations.AddField(
            model_name='follower',
            name='user2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
