# Generated by Django 4.1.1 on 2022-10-16 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_alter_follower_user2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='user2',
            new_name='usuario2',
        ),
    ]
