# Generated by Django 4.1.1 on 2022-10-16 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_rename_user2_follower_usuario2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='usuario2',
            new_name='user2',
        ),
    ]
