# Generated by Django 4.1.1 on 2022-09-30 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0005_comment_publication_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
