# Generated by Django 4.1.1 on 2022-09-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('category', models.CharField(max_length=15, verbose_name='category')),
                ('username', models.CharField(max_length=15, verbose_name='category')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email adress')),
                ('password', models.CharField(max_length=15, verbose_name='password')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='phone number')),
                ('can_post', models.BooleanField(blank=True, default=False)),
                ('is_admin', models.BooleanField(blank=True, default=False, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('is_staff', models.BooleanField(blank=True, default=False, null=True)),
                ('is_superuser', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('adress', models.CharField(max_length=100, verbose_name='adress')),
                ('district', models.CharField(max_length=15, verbose_name='district')),
                ('zip_code', models.CharField(max_length=9, verbose_name='zip_code')),
                ('city', models.CharField(max_length=60, verbose_name='city')),
                ('state', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, null=True, verbose_name='uf')),
                ('number', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
