# Generated by Django 4.1.1 on 2022-09-27 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adress',
        ),
    ]
