# Generated by Django 4.1.1 on 2022-10-07 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_delete_adress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('resume', models.CharField(blank=True, max_length=100, null=True)),
                ('site', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InformationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whoAreUs', models.CharField(blank=True, max_length=500, null=True)),
                ('ourObjective', models.CharField(blank=True, max_length=500, null=True)),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
        migrations.AddField(
            model_name='usermodel',
            name='information',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.information'),
            preserve_default=False,
        ),
    ]
