# Generated by Django 4.1.1 on 2022-10-07 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_information_informationproject_usermodel_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.information'),
        ),
    ]
