# Generated by Django 4.1.1 on 2022-10-07 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_usermodel_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='information',
        ),
    ]
