# Generated by Django 4.1.1 on 2022-10-07 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_remove_project_information_profile_and_more'),
        ('user', '0005_remove_usermodel_information'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InformationProject',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='photo',
            new_name='photo1',
        ),
        migrations.AddField(
            model_name='information',
            name='ourObjective',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='information',
            name='photo_profile',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='information',
            name='whoAreUs',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
