# Generated by Django 4.1.1 on 2022-10-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_information_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='password'),
        ),
    ]
