# Generated by Django 4.1.1 on 2022-11-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_usermodel_email_alter_usermodel_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='user',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='is_admin',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='is_staff',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='is_superuser',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
