# Generated by Django 4.1.1 on 2022-11-06 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_information_user_alter_usermodel_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
