# Generated by Django 4.1.1 on 2022-11-09 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_usermodel_created_at_usermodel_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2022-11-09 01:25:22.779'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default='2022-11-09 01:25:22.779'),
            preserve_default=False,
        ),
    ]
