# Generated by Django 4.1.1 on 2022-09-19 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0001_initial'),
        ('missionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionary',
            name='adress',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='informations.adress'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missionary',
            name='churchAddress',
            field=models.BooleanField(default=False),
        ),
    ]
