# Generated by Django 4.1.1 on 2022-09-20 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0001_initial'),
        ('missionary', '0002_missionary_adress_missionary_churchaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missionary',
            name='ministery',
        ),
        migrations.AddField(
            model_name='missionary',
            name='id_adress',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='missionary',
            name='adress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informations.adress'),
        ),
    ]
