# Generated by Django 4.1.1 on 2022-09-20 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missionary', '0003_remove_missionary_ministery_missionary_id_adress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missionary',
            name='churchAddress',
        ),
        migrations.RemoveField(
            model_name='missionary',
            name='id_adress',
        ),
    ]
