# Generated by Django 4.1.1 on 2022-09-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missionary', '0004_remove_missionary_churchaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionary',
            name='id_church',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
