# Generated by Django 4.1.1 on 2022-09-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missionary', '0005_missionary_id_church'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionary',
            name='id_adress',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
