# Generated by Django 4.1.1 on 2022-09-20 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0003_alter_church_user'),
        ('missionary', '0006_missionary_id_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionary',
            name='church',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='church.church'),
            preserve_default=False,
        ),
    ]
