# Generated by Django 4.1.1 on 2022-09-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missionary', '0007_alter_missionary_church'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionary',
            name='id_adress',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
