# Generated by Django 4.1.1 on 2022-09-20 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0001_initial'),
        ('missionary', '0008_alter_missionary_id_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionary',
            name='adress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='informations.adress'),
        ),
    ]
