# Generated by Django 4.1.1 on 2022-10-08 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_delete_informationproject_and_more'),
        ('missionary', '0010_missionary_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionary',
            name='information',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.information'),
        ),
    ]
